language: python

python:
  - "3.6"
services:
  - postgresql

# postgres 10
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

# end postgres
before_script:
  - export SECRET_KEY='my-api-key'
  - export JWT_SECRET_KEY='hhahahv/f-hej67'
  - export FLASK_ENV='testing'
  - psql -c 'create database test_storemanager;' -U postgres
env: 
- TEST_DB_URL="dbname='test_storemanager' user='postgres' host='localhost' password=''"
  global:
  - PGPORT=5432


install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nose

script:
  - nosetests --with-coverage --cover-package=app  && coverage report

after_success:
- coveralls